fix: change cmd in .air.toml to build instead of run
Melkeydev/go-blueprint pull request #120
Opened 2023-11-19 00:17 UTC by narasaka

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Prior to this commit, running `make watch` will result in the program running in the background without any way of killing it other than looking for its PID and killing that. This changes the `cmd` in the `.air.toml` file to run `make build` instead of `make run`, as well as changing `make build`'s output file to `tmp/main` instead of `main`.

## Description of Changes: 

- Change `cmd` in `.air.toml` to `make build`
- Change `make build`'s output to `tmp/main` instead of `main`

## Checklist

- [x] I have self-reviewed the changes being requested
- [x] I have updated the documentation (if applicable)

2023-11-19 15:51 UTC, 20pa5a1210 requested changes

2023-11-19 15:51 UTC, 20pa5a1210 commented on cmd/template/framework/files/air.toml.tmpl
> +  cmd = "make build"
`cmd = "go build -o ./tmp/main ./cmd/api"`

we can run directly like this instead using build command. imo making build file in tmp folder not a good practice

2023-11-19 15:51 UTC, 20pa5a1210 commented on cmd/template/framework/files/makefile.tmpl
> +	@go build -o tmp/main cmd/api/main.go
i think mostly people expect  build file to be in root of the folder so we should keep it that way

2023-11-19 17:47 UTC, 20pa5a1210 approved these changes

2023-11-20 03:06 UTC, Melkeydev approved these changes
lgtm

2023-11-20 03:06 UTC, merged