Implement [Fiber Framework] Middleware Rate Limiter
Melkeydev/go-blueprint pull request #206
Opened 2024-03-30 20:03 UTC by H0llyW00dzZ

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Implementing this rate limiter is pretty useful. I've been using it on my large RESTful APIs (500+ Handlers) with HTMX (for front end).

## Description of Changes: 

- [+] feat(program.go): add middleware limiter to fiber package
- [+] feat(fiber.go.tmpl): add rate limiter to HelloWorldWithRateLimiterHandler
- [+] feat(fiber.go.tmpl): add setRouteRateLimiter function to set rate limit configuration

## Checklist

- [X] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (if applicable)

2024-03-30 20:27 UTC, H0llyW00dzZ commented
some ci error lmao

```log
run golangci-lint
  Running [/home/runner/golangci-lint-1.55.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=fiber --timeout=5m] in [/home/runner/work/go-blueprint/go-blueprint/fiber] ...
  Error: : # fiber/internal/server
  internal/server/routes.go:9:2: time redeclared in this block
  	internal/server/routes.go:4:2: other declaration of time
  internal/server/routes.go:9:2: "time" imported and not used (typecheck)
  Error: could not import fiber/internal/server (-: # fiber/internal/server
  internal/server/routes.go:9:2: time redeclared in this block
  	internal/server/routes.go:4:2: other declaration of time
  internal/server/routes.go:9:2: "time" imported and not used) (typecheck)
  Error: could not import fiber/internal/server (-: # fiber/internal/server
  internal/server/routes.go:9:2: time redeclared in this block
  	internal/server/routes.go:4:2: other declaration of time
  internal/server/routes.go:9:2: "time" imported and not used) (typecheck)
  
  Error: issues found
  Ran golangci-lint in 12550ms
  ```

2024-04-04 12:43 UTC, briancbarrow commented
@H0llyW00dzZ can you add a limiter to all the frameworks?

2024-04-04 12:43 UTC, briancbarrow requested changes
Any changes like this would need to be applied to all frameworks.

2024-04-04 13:32 UTC, H0llyW00dzZ commented
> Any changes like this would need to be applied to all frameworks.

I haven't tested it yet for other frameworks, but currently, it works well for Fiber since it provides everything needed for web applications. Also Fiber's performance is particularly impressive for serverless applications when combined with Sonic for JSON decoding/encoding, marshaling, and unmarshaling.

2024-04-09 23:54 UTC, briancbarrow commented
@H0llyW00dzZ another concern with these PRs is that go-blueprint is intended to be an un-opinionated way of setting up a boilerplate Go project. I think this and the other PRs you have opened are good ideas though. 

I'll discuss with the team to decide if this is something we'd like to see.

2024-04-10 00:10 UTC, H0llyW00dzZ commented
> @H0llyW00dzZ another concern with these PRs is that go-blueprint is intended to be an un-opinionated way of setting up a boilerplate Go project. I think this and the other PRs you have opened are good ideas though.
> 
> I'll discuss with the team to decide if this is something we'd like to see. I just didn't want you to think we're ignoring your PRs.

@briancbarrow Yeah, it's fine. I came here to contribute so that I don't have to write the code again when using this boilerplate Go project for other RESTful APIs or front-end websites written in Go.

2024-04-10 00:17 UTC, H0llyW00dzZ commented
Also it might useful for anyone who need it that, and don't have write again

2024-04-17 01:49 UTC, briancbarrow commented on cmd/template/framework/files/routes/fiber.go.tmpl
> +	// Note: The rateLimiter requires a second parameter because it won't work if placed after the handler.
I'm not sure I understand this comment. Can you link to the documentation explaining this?

2024-04-17 02:03 UTC, briancbarrow commented
@H0llyW00dzZ after discussing it with @Melkeydev and @Ujstor we have decided that this feature is beyond the scope of what go-blueprint is supposed to be. It is intended to just be a scaffold from which to start projects. Users can add more robust features/middleware as they see fit. 

Thanks though for your PRs. We appreciate the contribution even if it ends up not being a fit.

2024-04-17 02:03 UTC, closed without merging