[DATABASE Template] [MYSQL] Implement Singleton Pattern
Melkeydev/go-blueprint pull request #209
Opened 2024-04-01 09:00 UTC by H0llyW00dzZ

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

This pull request implements the Singleton pattern for database connections, which is useful for reusing connections efficiently.

## Description of Changes: 

- [+] feat(mysql.tmpl): implement singleton pattern for dbInstance in New function

## Checklist

- [X] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (if applicable)

2024-04-01 09:12 UTC, H0llyW00dzZ commented
tested live in production:

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/b6afa5c3-68bb-49f9-95d9-9e8939a68689)

json:

```json
{"status":"up","open_connections":"2","idle":"1","max_lifetime_closed":"0","message":"It's healthy","in_use":"1","wait_count":"0","wait_duration":"0s","max_idle_closed":"0"}
```

2024-04-04 12:45 UTC, briancbarrow requested changes
@H0llyW00dzZ this is a good idea, but again we'd need the change applied to all database options.

2024-04-04 13:45 UTC, H0llyW00dzZ commented
@briancbarrow how about that MongoDB I've been Implement it ?

2024-04-04 13:59 UTC, H0llyW00dzZ commented
btw the ci error lmao

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/5eb14631-4de4-4712-897b-015dcc70155d)

2024-04-04 14:49 UTC, MitchellBerend commented
@H0llyW00dzZ I peaked at your action results real quick (for both #209 and #206) and github seems to be having issues right now.

https://www.githubstatus.com/history

2024-04-04 15:00 UTC, H0llyW00dzZ commented
> @H0llyW00dzZ I peaked at your action results real quick (for both #209 and #206) and github seems to be having issues right now.
> 
> https://www.githubstatus.com/history

@MitchellBerend it's unstable, look this a weird failure

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/9b0a5c76-ccc6-4f2e-a6be-94cfb84ca5d4)

2024-04-04 15:16 UTC, H0llyW00dzZ reviewed
# INFO

2024-04-04 15:16 UTC, H0llyW00dzZ commented on cmd/template/dbdriver/files/service/mongo.tmpl
> +	// Note: This is a different method for MongoDB compared to MySQL because, unlike MongoDB, you don't need to set `sync.Once` for MySQL.
> [!NOTE]
> Regarding MongoDB, I think it does not support connecting to multiple databases in a single connection like MySQL. In MySQL, you can connect to multiple databases using a single connection with a singleton pattern.

2024-04-04 15:27 UTC, H0llyW00dzZ commented
> It seems that GitHub is having issues with actions. I reran manually, and more checks are passing
> 
> https://www.githubstatus.com/history

this a weird

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/c0edb82a-8c5d-4e28-9bc1-51cc05d0856f)

2024-04-05 15:04 UTC, H0llyW00dzZ commented
now this one error again lmao

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/0abbec9b-187a-4feb-b262-b8850152e426)

2024-04-05 15:49 UTC, MitchellBerend commented
The cache posting issue is resolved in #213 since that removes that action from ci, not sure if this issue is related to yesterday's outage but maybe it's safer to wait for that pr to be merged.

2024-04-06 00:23 UTC, H0llyW00dzZ commented
> The cache posting issue is resolved in #213 since that removes that action from ci, not sure if this issue is related to yesterday's outage but maybe it's safer to wait for that pr to be merged.

@MitchellBerend The cache posting issue seems to be a race condition because Node.js cannot catch it. Also I don't recommend running CI/CD on Node.js, which is an interpreted language, especially for running lots of CI tasks like this. Unlike compiled languages that can run directly on the machine, such as Go, Node.js adds an extra layer of interpretation.

2024-04-06 03:01 UTC, Ujstor commented
By the end of the weekend, linter fix will be merged

2024-04-06 23:06 UTC, Ujstor commented
Updated workflow will be used on a new commit. I can't run it manually.

2024-04-07 19:29 UTC, H0llyW00dzZ commented
> Updated workflow will be used on a new commit. I can't run it manually.

@Ujstor this singleton pattern supports Fiber storage as well and provides perfect scalability for rate limiting.

- #206

For example:

```go
package database

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/storage/mysql/v2"

	_ "github.com/go-sql-driver/mysql"
	_ "github.com/joho/godotenv/autoload"
)

type Service interface {
	Health() map[string]string
	// RateLimiter returns the [fiber.Storage] interface for rate limiting.
	RateLimiter() fiber.Storage
}

type service struct {
	db          *sql.DB
	ratelimiter fiber.Storage
}

var (
	dbname     = os.Getenv("DB_DATABASE")
	password   = os.Getenv("DB_PASSWORD")
	username   = os.Getenv("DB_USERNAME")
	port       = os.Getenv("DB_PORT")
	host       = os.Getenv("DB_HOST")
	dbInstance *service
)

func New() Service {
	// Reuse Connection
	if dbInstance != nil {
		return dbInstance
	}

	// Opening a driver typically will not attempt to connect to the database.
	db, err := sql.Open("mysql", fmt.Sprintf("%s:%s@tcp(%s:%s)/%s", username, password, host, port, dbname))
	if err != nil {
		// This will not be a connection error, but a DSN parse error or
		// another initialization error.
		log.Fatal(err)
	}
	db.SetConnMaxLifetime(0)
	db.SetMaxIdleConns(50)
	db.SetMaxOpenConns(50)

	dbInstance = &service{
		db: db,
		ratelimiter: mysql.New(mysql.Config{
			Db:         db,
			Reset:      false,
			GCInterval: 10 * time.Second,
			Table:      "rate_limiter",
		}), // Initialize the rate limiter storage
	}
	return dbInstance
}

func (s *service) Health() map[string]string {
	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
	defer cancel()

	err := s.db.PingContext(ctx)
	if err != nil {
		log.Fatalf(fmt.Sprintf("db down: %v", err))
	}

	return map[string]string{
		"message": "It's healthy",
	}
}

// RateLimiter returns the [fiber.Storage] interface for rate limiting.
func (s *service) RateLimiter() fiber.Storage {
	return s.ratelimiter
}
```

In the database:

![image](https://github.com/Melkeydev/go-blueprint/assets/17626300/90dcb733-81cd-483d-88e2-15ca0913ca9f)

2024-04-07 20:19 UTC, H0llyW00dzZ commented
> @H0llyW00dzZ this is a good idea, but again we'd need the change applied to all database options.

@briancbarrow all done

2024-04-09 23:25 UTC, briancbarrow approved these changes

2024-04-10 03:51 UTC, H0llyW00dzZ commented
@briancbarrow by the way, for `Redis` and `MongoDB`, might not have to set a singleton pattern, I think, because they are both mostly used for caching. Using `sync.Once` might cause issues because, unlike other databases like `MySQL`, `PostgreSQL`, and `SQLite`, which are stable and can recover from connection issues (I've tested this by killing connections and database servers, and the Go routines can reconnect without using previous connection).

2024-04-10 11:33 UTC, briancbarrow commented
> @briancbarrow by the way, for `Redis` and `MongoDB`, might not have to set a singleton pattern, I think, because they are both mostly used for caching. Using `sync.Once` might cause issues because, unlike other databases like `MySQL`, `PostgreSQL`, and `SQLite`, which are stable and can recover from connection issues (I've tested this by killing connections and database servers, and the Go routines can reconnect without using previous connection).
> 

Okay. Will you remove that code from the Redis and Mongo files?

2024-04-10 20:22 UTC, H0llyW00dzZ commented
@briancbarrow done

2024-04-10 21:12 UTC, H0llyW00dzZ commented
Also, note that the singleton pattern is more stable and better suited for traditional SQL databases (e.g., `MySQL`, `PostgreSQL`, `SQLite`) compared to using a pooling pattern. On the other hand, the pooling pattern is more stable and better suited for NoSQL databases such as `Redis` and `MongoDB`, which are primarily used for caching.

2024-04-10 23:04 UTC, merged