Adding templ check in the make file
Melkeydev/go-blueprint pull request #241
Opened 2024-05-30 15:30 UTC by i3elj

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Under the Makefile there were no checks to see if templ was installed or not.

## Description of Changes: 

- I copied air's checks and changed to fit templ
- I removed the `@` cause make was unable to find the `templ` command

## Checklist

- [X] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (if applicable)

2024-05-31 13:25 UTC, Ujstor requested changes
There are two Makefiles. Please check the 'nondb' one. It also needs to be updated. We need to fix that and remove this logic from the codebase.

You have two options:
1. Just update 'nondbMakeFile.tmpl'
or
2. Make this PR even better and resolve the double Makefile issue

No pressure, either of them is great. Tnx for the PR

2024-06-12 15:08 UTC, Ujstor commented
@i3elj  I am just checking on your progress with the implementation. As I pointed out earlier, you can just update nondbMakeFile.tmpl with the same logic.

The plan is to resolve this Makefile issue in the near future, so you don't need to tackle that one.

There are also some conflicts that need to be resolved. I think you need to rebase.

2024-06-12 15:16 UTC, i3elj commented
@Ujstor Thanks for all the help. Right now I'm taking care of more urgent stuff in life and I can't see myself working on this, this month. I'll definitely take a look into this once I'm more free.

2024-06-18 20:10 UTC, Ujstor commented
I am closing it for now. Feel free to open a PR when you are ready. In the meantime, duble Makefile issue may be resolved

2024-06-18 20:10 UTC, closed without merging