Added a linting job that triggers on PR events
Melkeydev/go-blueprint pull request #28
Opened 2023-11-05 19:20 UTC by MitchellBerend

2023-11-05 19:20 UTC, MitchellBerend commented
Maybe you should also add branch protections that requires this job to pass so you don't shoot yourself in the foot as well. There is also a setting in there somewhere that only allows squash merges so the git history doesn't look like shit.

2023-11-07 20:55 UTC, Melkeydev commented on cmd/program/program.go
> +		}
I dont think this if /else is necessary

2023-11-07 20:55 UTC, Melkeydev commented on .github/workflows/linting.yml
> +        run: go mod download
Two install dependencies steps?

2023-11-07 20:56 UTC, Melkeydev commented on .github/workflows/linting.yml
> +name: Linting
I am wondering if this can be a pre-commit step? Just asking if this is necessary step to do here

2023-11-07 20:57 UTC, Melkeydev requested changes
Wondering about the execution of this Job and if we really need it

2023-11-08 05:55 UTC, MitchellBerend commented
This job isn't strictly necessary as a precommit script can do the same, but that could be skipped or forgotten. It's on the maintainer to install the script, I think having a safety net for that makes sense.

2023-11-09 21:53 UTC, Melkeydev approved these changes
LGTM

2023-11-09 21:53 UTC, merged