feat: Check if templ and tailwindcss commands are available before
Melkeydev/go-blueprint pull request #296
Opened 2024-08-24 12:07 UTC by jaswdr

building (#295)

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

When creating a new project for the first time, and having tailwindcss and templ options enable, the Makefile does not check if those commands are available. I'm adding a "check" step in the Makefile to do this, and redirect the user to installed them if they are not available.

## Description of Changes: 

- Makefile: Added `check` step if tailwindcss and templ options are enabled

## Checklist

- [x] I have self-reviewed the changes being requested
- [N/A] I have updated the documentation (check issue ticket #218)

2024-08-24 19:28 UTC, Ujstor commented
I saw the PR after I commented on the open issue ticket. First, we need to resolve the linter issue. I will leave my review shortly.

2024-08-25 10:07 UTC, Ujstor requested changes
The pipeline is fixed, it should pass on next push.

2024-08-25 10:08 UTC, jaswdr commented
Thanks, I'll take a look and check how to do it in Windows

2024-08-25 10:26 UTC, Ujstor commented
> Thanks, I'll take a look and check how to do it in Windows

It would be nice to have a Windows implementation….something like 30% of blueprint users are on Win

2024-09-16 22:47 UTC, Ujstor commented
here were other open issues related to the Makefile, and I resolved them all in one PR.

https://github.com/Melkeydev/go-blueprint/pull/306

2024-09-16 22:47 UTC, closed without merging