add graceful shutdown for the http server.
Melkeydev/go-blueprint pull request #308
Opened 2024-09-22 01:50 UTC by spankie

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

When the HTTP server is created it is important to have it gracefully shut down, and that is a boilerplate code that would be nice for go-blueprint to be able to add when the code is generated.

## Description of Changes: 

- add graceful shutdown for the HTTP server.
- change the error message printed when the server shuts down.

## Checklist

- [x] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (check issue ticket #218)

2024-09-23 19:06 UTC, Ujstor requested changes
Thanks for contributing to the project. There's one more main.go template for Fiber in /cmd/template/framework/files/fiber_main.go.tmpl

Changes need to be implemented across all frameworks and templates.

2024-09-27 19:19 UTC, Ujstor requested changes

2024-09-27 19:50 UTC, spankie commented on cmd/template/framework/files/main/main.go.tmpl
> +		panic(fmt.Sprintf("http server error: %s", err))
Yes, that's correct.

2024-09-28 11:13 UTC, Ujstor approved these changes
LGTM

2024-09-28 11:14 UTC, merged