Refactor: Replace printf-style function with print-style for dynamic format
Melkeydev/go-blueprint pull request #317
Opened 2024-10-17 03:21 UTC by MatthewAraujo

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

## Problem/Feature

Please include a description of the problem or feature this PR is addressing.

## Description of Changes: 

- Item 1
- Item 2

## Checklist

- [ ] I have self-reviewed the changes being requested
- [ ] I have updated the documentation (check issue ticket #218)

2024-10-17 18:14 UTC, Ujstor requested changes
This is a nice catch. We can remove the redundant syntax. I checked the other parts of the code, please include them in the PR, and we can merge it into the codebase:

docs/docs/endpoints-test/redis.md
docs/docs/endpoints-test/sql.md
docs/docs/endpoints-test/mongo.md

cmd/template/dbdriver/files/service/mysql.tmpl
cmd/template/dbdriver/files/service/postgres.tmpl
cmd/template/dbdriver/files/service/mongo.tmpl
cmd/template/dbdriver/files/service/redis.tmpl:73:53

2024-10-17 18:22 UTC, MatthewAraujo commented
> This is a nice catch. We can remove the redundant syntax. I checked the other parts of the code, please include them in the PR, and we can merge it into the codebase:
> 
> docs/docs/endpoints-test/redis.md docs/docs/endpoints-test/sql.md docs/docs/endpoints-test/mongo.md
> 
> cmd/template/dbdriver/files/service/mysql.tmpl cmd/template/dbdriver/files/service/postgres.tmpl cmd/template/dbdriver/files/service/mongo.tmpl cmd/template/dbdriver/files/service/redis.tmpl:73:53

Already did that!
Thank you for saying

2024-10-17 18:28 UTC, Ujstor commented
You can also add yourself on contributors.yml list.

2024-10-17 18:46 UTC, ccoVeille approved these changes

2024-10-17 18:48 UTC, Ujstor approved these changes
LGTM

2024-10-23 05:49 UTC, mdelapenya approved these changes

2024-10-28 17:21 UTC, merged