Trim whitespace for ProjectName
Melkeydev/go-blueprint pull request #40
Opened 2023-11-07 11:54 UTC by joshjms

I added one line to trim trailing and preceding whitespace.

This is my first time contributing code, much help will be appreciated. Sorry in advance!

2023-11-07 13:07 UTC, joshjms commented
![image](https://github.com/Melkeydev/go-blueprint/assets/83194022/64600467-abbd-495c-8e23-c2c09942e76a)

2023-11-07 21:14 UTC, Melkeydev commented
This is great!
However, you have some conflicts to resolve! Ill leave those for you! Congrats on your first OS PR!

2023-11-07 21:15 UTC, Melkeydev requested changes
Added a comment to address the comment added + the existing conflicts

2023-11-07 21:15 UTC, Melkeydev commented on cmd/program/program.go
> +	// Remove trailing whitespaces from ProjectName
Since the code is self-explanatory right below, this comment is not a value add! We can remove it  :)

2023-11-08 01:44 UTC, joshjms commented
Fixed! Thanks for the comment!

2023-11-08 05:40 UTC, Melkeydev approved these changes
LGTM!

2023-11-08 05:40 UTC, merged